<?php
/**
 * Created by PhpStorm.
 * User: 江艺勤
 * Date: 2020/12/10
 * Time: 15:46
 */
namespace cncn\insurance\cicp\service;

use cncn\insurance\cicp\service\CICPInsuranceGateway;
use cncn\insurance\common\InsuranceException;

/**
 * 保费试算
 * Class CaculatePremium
 * @package cncn\insurance\cicp\service
 */
class CaculatePremium extends CICPInsuranceGateway
{
    /**
     * 当前接口方法
     * @return string
     */
    protected function getMethod()
    {
        return 'CaculateTotalPremium';
    }

    /**
     * 投保接口地址
     * @return string
     */
    protected function getService()
    {
        return 'CIC1010';
    }

    /**
     *  组装试算报文
     * @param array $data
     * @return string
     */
    protected function dealRequestBody($data = [])
    {
        $transrno = $this->getService();
        $xml = <<<XML
<?xml version="1.0" encoding="GBK"?>
<INSUREQ>
  <HEAD>
    <TRANSRNO>{$transrno}</TRANSRNO>
    <PARTNERCODE>{$this->config['GW_CH_CODE']}</PARTNERCODE>
    <PARTNERSUBCODE>{$this->config['GW_CH_CODE']}</PARTNERSUBCODE>
  </HEAD>
  <MAIN>
    <PRODUCTCODE>{$data['productCode']}</PRODUCTCODE>
    <SERIALNUMBER>{$data['transNo']}</SERIALNUMBER>
    <TRANSRDATE>{$data['transDateTime']}</TRANSRDATE>
    <PRODUCTUNIT>{$data['productNum']}</PRODUCTUNIT>
    <EFFDATE>{$data['beginDateTime']}</EFFDATE>
    <TERMDATE>{$data['endDateTime']}</TERMDATE>
    <BBRUNIT>{$data['insuredNum']}</BBRUNIT>
    <APPCONTENT>试算</APPCONTENT>
    <TOLL>费用</TOLL>
  </MAIN>
</INSUREQ>
XML;
        return $xml;
    }


    /**
     * @param array $options
     * @return mixed
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function request(array $options)
    {
        return parent::request($options); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $options
     * @return array|void
     */
    protected function checkOptions(array $options = [])
    {
        if(empty($options['productCode'])){
            throw new InsuranceException('投保产品代码为空');
        }

        if(empty($options['transNo'])){
            throw new InsuranceException('业务流水号为空');
        }

        if(!$this->checkDateTime($options['transDateTime'])){
            throw new InsuranceException('撤销时间不合法');
        }

        if(empty($options['productNum'])){
            throw new InsuranceException('投保份数为空');
        }

        if(!$this->checkDateTime($options['beginDateTime'])){
            throw new InsuranceException('起保时间为空');
        }

        if(!$this->checkDateTime($options['endDateTime'])){
            throw new InsuranceException('终保时间为空');
        }

        if(strtotime($options['beginDateTime']) >= strtotime($options['endDateTime'])){
            throw new InsuranceException('起保时间不能大于终保时间');
        }

        if(empty($options['insuredNum'])){
            throw new InsuranceException('被保人数不能为空');
        }
    }
}