<?php
/**
 * Created by PhpStorm.
 * User: 江艺勤
 * Date: 2020/12/10
 * Time: 11:06
 */
namespace cncn\insurance\cicp\service;

use cncn\insurance\cicp\service\CICPInsuranceGateway;
use cncn\insurance\common\InsuranceException;

/**
 * 全部撤保-其实是批改注销
 * Class Cancel
 * @package cncn\insurance\cicp\service
 */
class Cancel extends CICPInsuranceGateway
{

    /**
     * 批改注销类型
     */
    private $cancelCode = 19;

    /**
     * 当前接口方法
     * @return string
     */
    protected function getMethod()
    {
        return 'Cancel';
    }


    /**
     * 投保接口地址
     * @return string
     */
    protected function getService()
    {
        return 'CIC005';
    }

    /**
     * 批改注销--组装撤保报文
     * @param array $data
     * @return array|string
     */
    protected function dealRequestBody($data = [])
    {
        $transrNo = $this->getService();
        $xml = <<<XML
<?xml version="1.0" encoding="GBK"?>
<INSUREQ>
    <HEAD>
        <TRANSRNO>{$transrNo}</TRANSRNO>
        <PARTNERCODE>{$this->config['GW_CH_CODE']}</PARTNERCODE>
        <PARTNERSUBCODE>{$this->config['GW_CH_CODE']}</PARTNERSUBCODE>
    </HEAD>
    <MAIN>
        <PRODUCTCODE>{$data['productCode']}</PRODUCTCODE>
        <SERIALNUMBER>{$data['transNo']}</SERIALNUMBER>
        <TRANSRDATE>{$data['transDateTime']}</TRANSRDATE>
        <POLNO>{$data['insuranceNo']}</POLNO>
        <CORRECTCODE>{$this->cancelCode}</CORRECTCODE>
    </MAIN>
    <HEALCORRECTINFO></HEALCORRECTINFO>
</INSUREQ>
XML;
        return $xml;
    }

    /**
     * 单线程单个投保
     * @param array $options
     * @return null
     */
    public function request(array $options)
    {
        return parent::request($options); // TODO: Change the autogenerated stub
    }

    /**
     * 投保参数校验
     * @param array $options
     * @return array
     */
    protected function checkOptions(array $options = [])
    {
        if(empty($options['productCode'])){
            throw new InsuranceException('投保产品代码为空');
        }

        if(empty($options['transNo'])){
            throw new InsuranceException('唯一业务流水号为空');
        }

        if(empty($options['insuranceNo'])){
            throw new InsuranceException('保单号为空');
        }

        if(!$this->checkDateTime($options['transDateTime'])){
            throw new InsuranceException('撤销时间不合法');
        }
    }
}