<?php
/**
 * Created by PhpStorm.
 * User: 江艺勤
 * Date: 2020/12/10
 * Time: 11:07
 */
namespace cncn\insurance\cicp\service;

use cncn\insurance\cicp\service\CICPInsuranceGateway;
use cncn\insurance\common\InsuranceException;

/**
 * 批改增减人员
 * Class EndorseChange
 * @package cncn\insurance\cicp\service
 */
class EndorseChange extends CICPInsuranceGateway
{

    /**
     * 批改新增人员标识
     */
    const BBR_INSERT = 'I';

    /**
     * 批改删除人员表示
     */
    const BBR_DELETE = 'D';

    /**
     * 批改新增文字标识
     */
    const ADD_CODE = 106;

    /**
     * 批改删除文字标识
     */
    const SUB_CODE = 107;

    /**
     * 批改替换文字标识
     */
    const REPLACE_CODE = 101;

    /**
     * 本次请求批改类型
     * @var int
     */
    private $endorseType = self::ADD_CODE;

    /**
     * 传入人员批改类型
     * @var string
     */
    private $bbrChangeType = self::BBR_INSERT;

    /**
     * 当前接口方法
     * @return string
     */
    protected function getMethod()
    {
        return 'EndorseChange';
    }
    /**
     * 投保接口地址
     * @return string
     */
    protected function getService()
    {
        return 'CIC005';
    }

    /**
     * 批改报文组装
     * @param array $data
     * @return array|string
     */
    protected function dealRequestBody($data = [])
    {
        $transrno  = $this->getService();

        $insuredTouristXml = $this->dealInsuredTourists($data['insuredTourists']);

        $xml = <<<XML
<?xml version="1.0" encoding="GBK"?>
<INSUREQ>
    <HEAD>
        <TRANSRNO>{$transrno}</TRANSRNO>
        <PARTNERCODE>{$this->config['GW_CH_CODE']}</PARTNERCODE>
        <PARTNERSUBCODE>{$this->config['GW_CH_CODE']}</PARTNERSUBCODE>
    </HEAD>
    <MAIN>
        <USERCODE/>
        <PRODUCTCODE>{$data['productCode']}</PRODUCTCODE>
        <SERIALNUMBER>{$data['transNo']}</SERIALNUMBER>
        <TRANSRDATE>{$data['transDateTime']}</TRANSRDATE>
        <POLNO>{$data['insuranceNo']}</POLNO>
        <EFFDATE>{$data['changeStartDate']}</EFFDATE>
        <CORRECTCODE>{$this->endorseType}</CORRECTCODE>
    </MAIN>
    <HEALCORRECTINFO>
        <BBRS>
            {$insuredTouristXml}
        </BBRS>
    </HEALCORRECTINFO>
</INSUREQ>
XML;
        return $xml;
    }

    /**
     * 处理批改人员报文
     * @param $tourists
     * @return string
     */
    private function dealInsuredTourists($tourists)
    {
        $insuredStr = '';

        foreach($tourists as $tourist){
            $insuredStr .= <<<INSURED_TOURIST
<BBR>
    <BBRNAME>{$tourist['insured_username']}</BBRNAME>
    <BBRSEX>{$tourist['insured_sex']}</BBRSEX>
    <BBRIDTYPE>{$tourist['insured_card_type']}</BBRIDTYPE>
    <BBRIDNO>{$tourist['insured_card_no']}</BBRIDNO>
    <BBRCORRECTTYPE>{$this->bbrChangeType}</BBRCORRECTTYPE>
</BBR>
INSURED_TOURIST;
        }

        return $insuredStr;
    }

    /**
     * 单线程单个投保
     * @param array $options
     * @return null
     */
    public function request(array $options)
    {
        return parent::request($options); // TODO: Change the autogenerated stub
    }

    /**
     * 批改原有保单新增
     * @param array $options
     * @return mixed
     */
    public function add(array $options)
    {
        return parent::request($options);
    }

    /**
     * 批改个人或多人撤保
     * @param array $option
     * @return mixed
     */
    public function sub(array $options)
    {
        $this->endorseType   = self::SUB_CODE;
        $this->bbrChangeType = self::BBR_DELETE;
        return parent::request($options);
    }

    /**
     * 批改替换
     * @param array $options
     * @return mixed
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replace(array $options)
    {
        throw new InsuranceException('批改替换不提供访问');
    }

    /**
     * 投保参数校验
     * @param array $options
     * @return array
     */
    protected function checkOptions(array $options = [])
    {
        if(empty($options['productCode'])){
            throw new InsuranceException('投保产品代码为空');
        }

        if(empty($options['transNo'])){
            throw new InsuranceException('业务流水号为空');
        }

        if(!$this->checkDateTime($options['transDateTime'])){
            throw new InsuranceException('撤销时间不合法');
        }
        
        if($this->checkDate($options['changeStartDate'])){
            throw new InsuranceException('批改生效日期不合法，必须为1970-01-01形式');
        }

        if(!$options['insuredTourists']){
            throw new InsuranceException('被保人员不能为空');
        }

        foreach($options['insuredTourists'] as $key => $tourist)
        {
            $index = $key + 1;
            if(empty($tourist['insured_username'])){
                throw new InsuranceException("第{$index}个被保人员姓名不能为空");
            }

            if(!in_array($tourist['insured_sex'], [1, 2, 3])){
                throw new InsuranceException("第{$index}个被保人员性别参数不合法");
            }

            if($tourist['insured_card_type'] < 1 || $tourist['insured_card_type'] > 25 && !in_array($tourist['insured_card_type'], ['53', '99'])){
                throw new InsuranceException("第{$index}个被保人员证件类型不合法");
            }

            if(empty($tourist['insured_card_no'])){
                throw new InsuranceException("第{$index}个被保人员证件号码不能为空");
            }
        }

    }
}