<?php
/**
 * Created by PhpStorm.
 * User: 江艺勤
 * Date: 2020/12/10
 * Time: 15:37
 */
namespace cncn\insurance\cicp\service;

use cncn\insurance\cicp\service\CICPInsuranceGateway;
use cncn\insurance\common\InsuranceException;

/**
 * 保单查询
 * Class Query
 * @package cncn\insurance\cicp\service
 */
class Query extends CICPInsuranceGateway
{
    /**
     * 当前接口方法
     * @return string
     */
    protected function getMethod()
    {
        return 'Query';
    }
    /**
     * 投保接口地址
     * @return string
     */
    protected function getService()
    {
        return 'CIC004';
    }

    /**
     *  组装查询报文
     * @param array $data
     * @return string
     */
    protected function dealRequestBody($data = [])
    {
        $transrno = $this->getService();
        $xml = <<<XML
<?xml version="1.0" encoding="GBK"?>
<INSUREQ>
    <HEAD>
        <TRANSRNO>{$transrno}</TRANSRNO>
        <PARTNERCODE>{$this->config['GW_CH_CODE']}</PARTNERCODE>
        <PARTNERSUBCODE>{$this->config['GW_CH_CODE']}</PARTNERSUBCODE>
    </HEAD>
    <MAIN>
        <POLNO>{$data['insuranceNo']}</POLNO>
        <SERIALNUMBER>{$data['transNo']}</SERIALNUMBER>
    </MAIN>
</INSUREQ>
XML;
        return $xml;

    }

    /**
     * @param array $options
     * @return mixed
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function request(array $options)
    {
        return parent::request($options); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $options
     * @return array|void
     */
    protected function checkOptions(array $options = [])
    {
        if(empty($options['insuranceNo'])){
            throw new InsuranceException('保单号为空');
        }

        if(empty($options['transNo'])){
            throw new InsuranceException('投保流水号为空');
        }
    }
}